---
- name: Ensure paperless group exists
  ansible.builtin.group:
    name: "{{ paperless_user }}"
    state: present
    system: yes
  tags: user

- name: Ensure paperless user exists
  ansible.builtin.user:
    name: "{{ paperless_user }}"
    group: "{{ paperless_user }}"
    create_home: yes
    home: "/home/{{ paperless_user }}"
    system: yes
  tags: user

- name: Install UID/GID mapping helpers on CentOS Stream 10
  ansible.builtin.package:
    name: shadow-utils
    state: present
  become: true

- name: Ensure subuid mapping for paperless user
  ansible.builtin.lineinfile:
    path: /etc/subuid
    line: "{{ paperless_user }}:100000:65536"
    create: yes
    state: present
  become: true

- name: Ensure subgid mapping for paperless user
  ansible.builtin.lineinfile:
    path: /etc/subgid
    line: "{{ paperless_user }}:100000:65536"
    create: yes
    state: present
  become: true

- name: Kill paperless user’s current loginctl session
  ansible.builtin.command:
    cmd: loginctl kill-user {{ paperless_user }}
  become: true

- name: Ensure systemd user unit directory exists
  ansible.builtin.file:
    path: "/home/{{ paperless_user }}/.config/systemd/user"
    state: directory
    owner: "{{ paperless_user }}"
    group: "{{ paperless_user }}"
    mode: '0755'
  tags: user

- name: Ensure lingering for paperless user
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ paperless_user }}
    creates: "/var/lib/systemd/linger/{{ paperless_user }}"
  tags: user
