---
- name: Ensure custom Podman network exists
  containers.podman.podman_network:
    name: paperless-net
    state: present
  become: true

- name: Ensure Redis image is present
  containers.podman.podman_image:
    name: docker.io/library/redis:8
  become: true

- name: Create Redis container (broker)
  containers.podman.podman_container:
    name: paperless-broker
    image: docker.io/library/redis:8
    state: created
    publish:
      - "6380:6379"
    volume:
      - /srv/paperless/redisdata:/data:Z
    restart_policy: always
    network: paperless-net
  become: true

- name: Ensure PostgreSQL image is present
  containers.podman.podman_image:
    name: docker.io/library/postgres:17
  become: true

- name: Create PostgreSQL container (db)
  containers.podman.podman_container:
    name: paperless-db
    image: docker.io/library/postgres:17
    state: created
    volume:
      - /srv/paperless/pgdata:/var/lib/postgresql/data:Z
    env:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    restart_policy: always
    network: paperless-net
  become: true

- name: Ensure Gotenberg image is present
  containers.podman.podman_image:
    name: docker.io/gotenberg/gotenberg:8.20
  become: true

- name: Create Gotenberg container
  containers.podman.podman_container:
    name: paperless-gotenberg
    image: docker.io/gotenberg/gotenberg:8.20
    state: created
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    restart_policy: always
    network: paperless-net
  become: true

- name: Ensure Tika image is present
  containers.podman.podman_image:
    name: ghcr.io/paperless-ngx/tika:latest
  become: true

- name: Create Tika container
  containers.podman.podman_container:
    name: paperless-tika
    image: ghcr.io/paperless-ngx/tika:latest
    state: created
    restart_policy: always
    network: paperless-net
  become: true
