---
- name: Generate systemd unit file for Paperless webserver container
  ansible.builtin.command:
    cmd: podman generate systemd --name paperless-webserver --files --restart-policy=always
    chdir: /root  # Or any temporary writeable dir
  become: true
  register: systemd_unit_result
  changed_when: systemd_unit_result.rc == 0
  tags: systemd

- name: Copy generated unit to systemd system directory
  ansible.builtin.copy:
    src: "/root/container-paperless-webserver.service"
    dest: "/etc/systemd/system/container-paperless-webserver.service"
    remote_src: true
    owner: root
    group: root
    mode: "0644"
  become: true
  tags: systemd

- name: Reload systemd and enable/start Paperless container
  ansible.builtin.systemd:
    name: container-paperless-webserver.service
    scope: system
    enabled: true
    daemon_reload: true
    state: started
  become: true
  tags: systemd
