---
- name: Install useful tools on CentOS 10
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ensure packages are installed
      package:
        name:
          - git
          - ripgrep
          - tmux
          - bat
          - jq
        state: present

