---
- name: Configure CentOS 10 target VMs
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: "patrick"

  tasks:

    - name: Refresh package metadata
      dnf:
        update_cache: yes

    - name: Enable CRB repository via dnf config-manager (fallback)
      command: dnf config-manager --set-enabled crb
      when: not ansible_facts.packages['centos-stream-crb'] is defined

    - name: Enable EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Remove subscription-manager package
      dnf:
        name: subscription-manager
        state: absent

    - name: Install Development Tools group (optional)
      dnf:
        name: "@Development Tools"
        state: present

    - name: Add default user to wheel group
      user:
        name: "{{ ansible_user }}"
        groups: wheel
        append: yes

    - name: Enable passwordless sudo for wheel group
      lineinfile:
        path: /etc/sudoers.d/wheel-nopasswd
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        create: yes
        validate: 'visudo -cf %s'
        mode: '0440'

    - name: Ensure alias is set globally (so that all users have the alias)
      lineinfile:
        path: "/etc/profile.d/custom_aliases.sh"
        line: "alias l='ls -alh'\n"
        create: yes
        mode: '0644'

    - name: Ensure packages are installed
      package:
        name:
          - git
          - ripgrep
          - tmux
          - bat
          - jq
        state: present
