---
- name: Install useful tools on CentOS 10
  hosts: all
  become: yes

  tasks:
    - name: Ensure packages are installed
      package:
        name:
          - git
          - ripgrep
          - tmux
        state: present

