---
# - import_playbook: playbooks/setup-base.yml
# - import_playbook: playbooks/install-podman.yml
# - import_playbook: playbooks/install-cockpit.yml
# - import_playbook: playbooks/install-caddy.yml
# - import_playbook: playbooks/install-readeck.yml
# - import_playbook: playbooks/install-readeck-backup.yml
# - import_playbook: playbooks/paperless-teardown.yml
# - import_playbook: playbooks/paperless-install.yml
- import_playbook: playbooks/paperless-ngx-install.yml
