- name: Ensure Caddy config directory exists
  file:
    path: "{{ caddy_config_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Copy Caddyfile to config directory
  copy:
    src: Caddyfile
    dest: "{{ caddy_config_dir }}/Caddyfile"
    owner: "{{ ansible_user }}"
    mode: '0644'

- name: Run Caddy in Podman
  containers.podman.podman_container:
    name: caddy
    image: docker.io/library/caddy:2
    state: started
    detach: true
    restart_policy: unless-stopped
    ports:
      - "8080:80"
    volume:
      - "{{ caddy_config_dir }}/Caddyfile:/etc/caddy/Caddyfile:ro,Z"
