---
- name: Ensure packages are installed (dependencies for docker)
  become: true
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repository
  become: true
  ansible.builtin.command: >
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker Engine
  become: true
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker
  become: true
  service:
    name: docker
    state: started
    enabled: yes

- name: Verify docker compose works
  ansible.builtin.shell: docker compose version
  register: docker_compose_version
  changed_when: false

- name: Add ansible_user to group `docker`
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Ensure packages are installed (dependencies for docker)
  become: true
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repository
  become: true
  ansible.builtin.command: >
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker Engine
  become: true
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker
  become: true
  service:
    name: docker
    state: started
    enabled: yes

- name: Verify docker compose works
  ansible.builtin.shell: docker compose version
  register: docker_compose_version
  changed_when: false

- name: Add ansible_user to group `docker`
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
