- name: diun setup
  hosts: nepenthes,urchin
  become: yes
  vars_files:
    - ../inventories/development/group_vars/diun/0_setup.yml
  vars:
    ansible_user: "{{ diun_docker_user }}"

  roles:
    # - common
    # - system
    # - docker
    - diun-docker
