- name: paperless-ngx
  hosts: nepenthes
  become: true
  vars_files:
    - ../inventories/development/group_vars/paperless-docker/0_setup.yml
  vars:
    ansible_user: "{{ paperless_docker_user }}"

  roles:
    - common
    - system
    - docker
    - paperless-docker
